apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todolist-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: todolist-dev
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: 'https://rht-labs.com/todolist/' # Source of Helm chart: Helm chart repository
    chart: todolist # Helm chart name
    targetRevision: 1.1.0 # Helm chart version
    helm:
      valueFiles:
      - $values/todolist/values/values-dev.yaml # values.yaml in a sperate Helm values Git repository
  - repoURL: 'https://github.com/xdevops-caj-lab-gitops-cd/gitops-example-apps.git' # Source of Helm values Git repository
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated: {}
