apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todolist-git
  namespace: openshift-gitops
spec:
  destination:
    namespace: todolist-git
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: todolist/chart
    repoURL: https://github.com/xdevops-caj-lab-gitops-cd/gitops-example-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
