apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-namespace-v2
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/xdevops-caj-lab-gitops-cd/gitops-example-iac
      revision: HEAD
      directories:
      - path: cluster-config/namespaces-v2/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/xdevops-caj-lab-gitops-cd/gitops-example-iac
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated: {}
