apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-bgd
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
            namespace: bgd-dev
            path: bgd/overlays/dev
            name: app-bgd-dev
          - cluster: in-cluster
            url: https://kubernetes.default.svc
            namespace: bgd-sit
            path: bgd/overlays/sit
            name: app-bgd-sit
  template:
    metadata:
      name: '{{name}}'
    spec:
      # assign to a specific ArgoCD appproject
      project: appproj-bgd
      source:
        repoURL: https://github.com/xdevops-caj-lab-gitops-cd/gitops-example-apps.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated: {}
