apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: appproj-bgd
  namespace: openshift-gitops
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: 'bgd-*'
    name: in-cluster
    server: https://kubernetes.default.svc
  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    policies:
    - p, proj:appproj-bgd:read-only, applications, get, appproj-bgd/*, allow
    groups:
    - bgd-group
  syncWindows:
  - kind: allow
    schedule: '* * * * *'
    duration: 1h
    clusters:
      - in-cluster