apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic
  namespace: openshift-gitops
spec:
  destination:
    namespace: spring-petclinic
    server: https://kubernetes.default.svc
  project: default
  source:
    path: spring-petclinic
    repoURL: https://github.com/xdevops-caj-lab-gitops-cd/gitops-example-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
